"""empty message

Revision ID: a64ff3b48970
Revises: 
Create Date: 2021-07-07 15:41:58.836975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64ff3b48970'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('rg', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('espec', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('contato', sa.Integer(), nullable=False),
    sa.Column('registro', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('registro'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('receita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remedio', sa.String(length=50), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('endereco', sa.String(length=50), nullable=False),
    sa.Column('plano', sa.String(length=20), nullable=False),
    sa.Column('estado_civil', sa.String(length=10), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('contato', sa.Integer(), nullable=False),
    sa.Column('rg', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contato'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('association_med_pac',
    sa.Column('medico', sa.Integer(), nullable=True),
    sa.Column('paciente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['paciente'], ['paciente.id'], )
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=8), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data', sa.String(length=8), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exame')
    op.drop_table('consulta')
    op.drop_table('association_med_pac')
    op.drop_table('paciente')
    op.drop_table('receita')
    op.drop_table('medico')
    # ### end Alembic commands ###
